language: go
go:
- "1.11.1"
install:
- go get -v github.com/gohugoio/hugo
- npm install -g bower
- bower install
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: rgRcL2J6VB5TDpLKaEjjvjmu8BjkPwcGVMhfIDiRgaiULRtc9TrP8PXJYhNgDo2bl1m1yABf8kIRzFaKfMGzY88RyRISh0ZO6K9tZWXD8sTVOEWG5kITKvsPA8jZ/3qzaINLNwz3vsVpwxLtfgGfssfZCbXSWpDd4G8zKWvHCNwtuUr7W/BmREpd12HURcfRfia0C0dlk9SQN9WLL2pLrROeFMJRD9QXguJxoSOJx7BPOTzQCxk6qqppAyiR8kiMVPBw43zKIHnNyfRVCDOO0ylUYSIodu+WdBhd7HdvuevDMauoFsgR2iHGgmoSWj0gHrUqDIHhD2BM3aOdGvEk+OSAiJHUKQDFcNZ+kCl0oDS6NqHa4n93tvryKUD/eUJZwanEvLbL55dZIs7tazFSVw5W9zHshJhtO+ewYoyBXVUIp7uzviJ6cLgHlvr1gA8fI4JQO7at+R70OaR6rs3FHxH2UFI7QjLuXcLM7BJouIfZPMd2yi/wiSfYYktrOrg6EHFN279jit5KABJdXe+rr3yliPoCnEfJ1Jmw8yPRDAoqAUw8VHMtxwEyZBUFQe5VEemeS10wGHfn9iXREn4ujPdR1luMLbKPZWSBqETGGlDBIrd44Lpc0sOP7YUSXbRkYG5wSVQhaBqGbDJ5Lt0Qcq3jbxjUMXxjnTGzGgVr2Ds=
  - secure: bzF26+Sihkm4yvgOtK7+eux7Arb+4IKALYLK5rn5c0nXcYF7z84mR6X4+yFxCrX8+aJmvyn/Hb65cquHD1ivHIsniF+tgVpMmmw9UVqtCIZfHMyFn9s8rI/3uwkRVLvnS8od3zL1Qrrs2ttJRYv1ra7QBb5M4E3w32shVTiP134eVWfmBpxs2xOiiSH962nyH1SL6cfRKZ9XpB2E8Qs0zxAbkONHkgqmjmNH2Zsl6nQyf9qOEzyh5T/UAEaXvI/2Nj5glNcygt4oM6vXSKJWJzArQiMNF5iui5v6G3/u1m//Q7QxCv1/KojHW8shMkQepVksI9ck9JDxaprqFvJClVrtVzsE3D0rGTWmjj/j8tKR50CgSKcSLpyAvaB8ab67mo2oucR60J2t1dmLFWeAccfawX60WO/8UQJuwGYh9kDJyz8ScCfbKIu5FW/lrmqej6pNLd00F+XD9LTi8ZofQJIkYsTiiYZzpZDm7XQG1doP4y32f90vaRHH/V6dCg0TCfa/KkCPLbNRVl5G63IkK/R2BJ2gPQJOdj+dWt2p2lY53voKNaWnF+g/UxRuD7YFgm3+ifVD73bonwCfBFmslJmTBJE9owyiLWO1a0FPwca5Osi8RjxnsvEq59ZNCzoTQWYz1aVkZotuaDUVqhyG/18DxQCKOeqZUH+a9X5aIO8=
